name: Tests automáticos en rama personal

on:
  push:
    branches:
      - 'Santi/*' 

jobs:
  test:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          
      - name: Verifica con Maven
        run: mvn --batch-mode --update-snapshots verify --file pom.xml

      - name: Generar informe de pruebas
        run: mvn surefire-report:report-only

      - name: Publicar informe de pruebas
        uses: actions/upload-artifact@v2
        with:
          name: Informe de tests
          path: target/site/surefire-report.html
